apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: matrikkel-rest-api-eiendom
  namespace: matrikkel-main
spec:
  image: "{{image}}"
  port: 5000
  ingresses:
    - eiendom.atkv3-dev.kartverket-intern.cloud

  # TODO, ingen replicas i dev i smia-apps. Mulig vi ikke trenger dev?
  replicas: 0
  resources:
    limits:
      memory: 2G
    requests:
      cpu: 100m
      memory: 256M

  liveness:
    failureThreshold: 3
    initialDelay: 0
    path: /eiendom/v1/healthx
    period: 10
    port: 5000
    successThreshold: 1
    timeout: 1
  readiness:
    failureThreshold: 3
    initialDelay: 0
    path: /eiendom/v1/healthz
    period: 10
    port: 5000
    successThreshold: 1
    timeout: 1
  prometheus:
    allowAllMetrics: false
    path: /eiendom/v1/metrics
    port: 5000
    scrapeInterval: 60s

  databases:
    - name: matrikkel-rest-api-eiendom
      envName: EIENDOM_DB_URI

  env:
    - name: EIENDOM_DB_USER
      value: "dbles"
    - name: EIENDOM_DB_PASSWORD
      gsmSecretName: "dev-matrikkel-rest-api-eiendom-db-user-password"
    - name: EIENDOM_INGRESS
      value: eiendom.atkv3-dev.kartverket-intern.cloud
---
# SKIP Støtter ikke path-routing på tvers av namespaces
# Derfor må vi manuelt koble oss mot en gateway for å trafikk inn til appen våres.
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: api-ingresses
spec:
  gateways:
    - istio-gateways/api-test-kartverket-ingress
  hosts:
    - api.test.kartverket.no
  http:
    - name: "matrikkel-rest-api-eiendom"
      match:
        - port: 443
          uri:
            prefix: "/eiendom/v1"
      route:
        - destination:
            host: "matrikkel-rest-api-eiendom"
            port:
              number: 5000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "matrikkel-rest-api-eiendom-allow-tcp"
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              'kubernetes.io/metadata.name': 'istio-gateways'
          podSelector:
            matchLabels:
              istio: ingressgateway
      ports:
        - port: 5000
          protocol: TCP
  podSelector:
    matchLabels:
      app: "matrikkel-rest-api-eiendom"
  policyTypes:
    - Ingress
