# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "matrikkel-rest-api-eiendom"
  tags:
  - "public"
spec:
  type: "service"
  lifecycle: "production"
  owner: "heimdall"
  system: "matrikkel"
  providesApis:
  - "matrikkel-rest-api-eiendom-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "security_champion_matrikkel-rest-api-eiendom"
  title: "Security Champion matrikkel-rest-api-eiendom"
spec:
  type: "security_champion"
  parent: "eiendom_security_champions"
  members:
  - "lislei"
  children:
  - "resource:matrikkel-rest-api-eiendom"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "matrikkel-rest-api-eiendom"
  links:
  - url: "https://github.com/kartverket/matrikkel-rest-api-eiendom"
    title: "matrikkel-rest-api-eiendom på GitHub"
spec:
  type: "repo"
  owner: "security_champion_matrikkel-rest-api-eiendom"
  dependencyOf:
  - "component:matrikkel-rest-api-eiendom"
---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "matrikkel-rest-api-eiendom-api"
  tags:
  - "public"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "heimdall"
  definition: |
    openapi: "3.0.0"
    info:
        title: matrikkel-rest-api-eiendom API
    paths:
