# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "matrikkel-rest-api-eiendom"
  tags:
  - "public"
spec:
  type: "service"
  lifecycle: "production"
  owner: "heimdall"
  system: "m22"
  providesApis:
  - "matrikkel-rest-api-eiendom-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "matrikkel-rest-api-eiendom-api"
  tags:
  - "public"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "heimdall"
  system: "m22"
  definition: |
    openapi: "3.0.0"
    info:
        title: matrikkel-rest-api-eiendom API
    paths:
