
test_name: eiendom med 3 teiger

strict:
  - headers:off
  - json:off

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '3413-339/42'
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        features:
          - properties:
              objekttype: 'Teig'

---

test_name: takle 0 som et tall i matrikkelstrengsøk, komplett retur

strict:
  - headers:off
  - json:on

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '3413-6/501/0/2'
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        type: 'FeatureCollection'
        features:
          - type: 'Feature'
            properties:
              kommunenummer: '3413'
              gardsnummer: 6
              bruksnummer: 501
              festenummer: 0
              seksjonsnummer: 2
              hovedområde: true
              lokalid: 34281284
              oppdateringsdato: "2020-06-16T03:58:58"
              teigmedflerematrikkelenheter: false
              uregistrertjordsameie: false
              objekttype: 'Teig'
              matrikkelnummertekst: "6/501/0/2"
              nøyaktighetsklasseteig: "Gult"
            geometry:
              type: 'Point'
              coordinates:
                - 11.11041
                - 60.78311


---

test_name: matrikkelsøk, komplett retur med område, ikke punkt

strict:
  - headers:off
  - json:on

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '3413-6/518'
        omrade: true
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        type: 'FeatureCollection'
        features:
          - type: 'Feature'
            properties:
              kommunenummer: '3413'
              gardsnummer: 6
              bruksnummer: 518
              festenummer: 0
              seksjonsnummer: 0
              hovedområde: true
              lokalid: 34281734
              oppdateringsdato: "2020-06-16T03:58:58"
              teigmedflerematrikkelenheter: false
              uregistrertjordsameie: false
              objekttype: 'Teig'
              matrikkelnummertekst: "6/518"
              nøyaktighetsklasseteig: "Gult"
            geometry:
              type: 'Polygon'
              coordinates:
                - !anylist


---


test_name: Søk på feilformatert matrikkelnummer

strict:
  - headers:off
  - json:on

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '3413-6/501\0/2'
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 400
      json:
        errors:
          message: 'Ugyldig(e) tegn i søkeparameteret. Husk på at matrikkelnummer bruker skråstreker /, og ikke bakstreker (omvendt skråstrek) \.'


---


test_name: Søk på feilformatert matrikkelnummer, kun 2 elementer.

strict:
  - headers:off
  - json:on

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '3413-6'
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 400
      json:
        errors:
          message: 'Mangler skråstrek i matrikkelnummeret etter gardsnummeret.'


---


test_name: Søk på feilformatert matrikkelnummer, kun /.

strict:
  - headers:off
  - json:on

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '/'
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 400
      json:
        errors:
          message: 'Feil i matrikkelnummeret, forventer en bindestrek mellom kommunenummer-gardsnummer'


---

test_name: Søk på matrikkelnummer med 0 treff

strict:
  - headers:off
  - json:on

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '9999-555/22'
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        type: "FeatureCollection"
        features: []

---

test_name: punktsøk, finn eiendommer i riktig distanse

strict:
  - headers:off
  - json:off

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/punkt"
      params:
        nord: 6746481.09
        ost: 286775.27
        koordsys: 25833
        radius: 135
        treffPerSide: 50
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        eiendom:
          - objekttype: 'Teig'
            meterFraPunkt: 133

---

test_name: punktsøk, finn eiendom med "falsk" matrikkelnummer 0/1

strict:
  - headers:off
  - json:off

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/punkt"
      params:
        nord: 58.51245
        ost: 5.84620469
        koordsys: 4258
        radius: 10
        treffPerSide: 50
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        eiendom:
          - objekttype: 'Teig'
            meterFraPunkt: 0
            kommunenummer: '1119'
            gardsnummer: null
            bruksnummer: null
            festenummer: null
            seksjonsnummer: null

---

test_name: søk på de individuelle elementene i et matrikkelnummer

strict:
  - headers:off
  - json:off

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        kommunenummer: 3413
        gardsnummer: 6
        bruksnummer: 501
        festenummer: 0
        seksjonsnummer: 2
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        features:
          - properties:
              objekttype: 'Teig'
              matrikkelnummertekst: "6/501/0/2"


---

test_name: Hovedteig først. Treff på flere eiendom med flere teiger

strict:
  - headers:off
  - json:on

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '3454-107/5'
        filtrer: "features.properties.hovedområde"
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        features:
          - properties:
              hovedområde: true
          - properties:
              hovedområde: false
          - properties:
              hovedområde: false
          - properties:
              hovedområde: false
          - properties:
              hovedområde: false
          - properties:
              hovedområde: false
          - properties:
              hovedområde: false

---

test_name: Seksjon uten areal, returner eiendommen som seksjonen tilhører i stedet for.

strict:
  - headers:off
  - json:off

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '3413-6/518/0/2'
      method: GET
      timeout: 2
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        type: 'FeatureCollection'
        features:
          - type: 'Feature'
            properties:
              kommunenummer: '3413'
              gardsnummer: 6
              bruksnummer: 518
              festenummer: 0
              seksjonsnummer: 0
              hovedområde: true
              lokalid: 34281734
              objekttype: 'Teig'
              matrikkelnummertekst: "6/518"


---

test_name: Eiendom med både teig og anleggsprojeksjonsflate

strict:
  - headers:off
  - json:off

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '0301-377/4'
        filtrer: "features.properties.objekttype"
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        features:
          - properties:
              objekttype: 'Teig'
          - properties:
              objekttype: 'Anleggsprojeksjonsflate'


---

test_name: punktsøk, delt teig

strict:
  - headers:off
  - json:off

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/punkt"
      params:
        nord: 60
        ost: 11
        koordsys: 4326
        radius: 1
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        eiendom:
          - objekttype: 'Teig'
            meterFraPunkt: 0
            teigmedflerematrikkelenheter: true
            matrikkelnummertekst: "46/1,7"
          - objekttype: 'Teig'
            meterFraPunkt: 0
            teigmedflerematrikkelenheter: true
            matrikkelnummertekst: "46/1,7"

---

test_name: punktsøk, hent teiger innenfor radius

strict:
  - headers:off
  - json:off

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/punkt/omrader"
      params:
        nord: 59.928
        ost: 10.723
        koordsys: 4258
        radius: 10
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        features:
          - properties:
              meterFraPunkt: 0
              matrikkelnummertekst: "215/81"
        features:
          - properties:
              meterFraPunkt: 2
              matrikkelnummertekst: "215/61"




---

test_name: Transformer respons, inkluder crs-element

strict:
  - headers:off
  - json:off

stages:
  - name: get
    request:
      url: "{tavern.env_vars.TAVERN_TEST_URL}/geokoding"
      params:
        matrikkelnummer: '3413-6/501/0/2'
        utkoordsys: 25833
      method: GET
      timeout: 1
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        crs:
          type: 'name'
          properties:
            name: 'EPSG:25833'
        type: FeatureCollection
        features:
          - type: 'Feature'
            properties:
              matrikkelnummertekst: "6/501/0/2"
            geometry:
              type: 'Point'
              coordinates:
                - 288280.5061
                - 6744905.414
