name: Build, push and deploy to ArgoCD
on:
  push:
    branches: ["main"]

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: kartverket/eiendom

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
      id-token: write

    outputs:
      version: ${{ steps.set_output.outputs.version }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2

      - name: Login to Github Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee #4.2.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b #6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image and push
        id: build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f #7.1.0
        with:
          context: .
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }} , ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: true

      - name: Summarize Image Digest and Set Output
        id: set_output
        run: |
          echo "Full Image URL: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}@${{ steps.build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
          echo "version=${{ steps.tag_version.outputs.new_tag }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  deploy-argo:
    needs: build
    permissions:
      id-token: write
    uses: kartverket/smia-apps/.github/workflows/release-app-octo-sts.yml@main
    with:
      application: eiendom
      version: ${{ needs.build.outputs.version }}
      namespace: "smia-tjenester-main"
      deploy_dev: true
      identity: 'matrikkel-rest-api-eiendom'
