name: Sikkerhetsscanning av images

on:
    workflow_dispatch:
    schedule:
        - cron: '00 1 * * *'  # 01:00 each day.

jobs:
    pharos:
        name: Run Pharos
        permissions:
            actions: read
            packages: read
            contents: read
            security-events: write
        runs-on: ubuntu-latest

        steps:
            - name: Finn siste GHCR image-tag
              id: latest
              uses: kartverket/matrikkel-actions/find-latest-image@main
              with:
                  image: eiendom # GHCR pakkenavn

            - name: Run Pharos
              uses: kartverket/pharos@e5a5cf71dd41384d6d62c7d9b387851c0457e81b # v0.6.4
              with:
                trivy_category: eiendom
                disable_severity_check: 'true' # Ikke blokker byggeløyper ved evt sårbarheter!
                image_url: ghcr.io/kartverket/eiendom:${{ steps.latest.outputs.tag }}
